version: '3.6'

services:
  client:
    build: 
      context: ./services/client
      dockerfile: Dockerfile-dev.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - './services/client:/srv/services/client'

  test:
    build: 
      context: ./services/client
      dockerfile: Dockerfile-dev.Dockerfile
    volumes:
      - /app/node_modules
      - './services/client:/srv/services/client'
    command: ["yarn", "run", "test"]
  

